name: Benchmarking

on:
  workflow_dispatch:
    inputs:
      never_rounds:
        required: false
        description: Never Rounds (1k)
        default: '25'
        type: string
      once_rounds:
        required: false
        description: Once Rounds (1k)
        default: '0.5'
        type: string
      java_versions:
        required: false
        description: Java Versions (json)
        default: '[ 24, 21, 11 ]'
        type: string
      lucee_versions:
        required: false
        description: Lucee Versions (json)
        default: '[ "7.0/snapshot/zero", "6.2.1/snapshot/zero", "6.2.0/stable/zero", "6.1/stable/zero", "5.4/stable/light" ]'
        type: string
      java_distribution:
        required: false
        description: Java Distribution
        type: string
        default: 'temurin'
      benchmark_filter:
        required: false
        description: Test Filter
        type: string
      exeLog:
         description: Execution Log
         required: true
         default: 'none'
         type: choice
         options:
           - none
           - console
           - debug
  workflow_call:

run-name: "Benchmarking: ${{ github.event.inputs.never_rounds }}k rounds, distro ${{ github.event.inputs.java_distribution }}, exeLog: ${{ github.event.inputs.exeLog }}"

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        luceeVersion: ${{ fromJSON(github.event.inputs.lucee_versions) }}
        javaVersion: ${{ fromJSON(github.event.inputs.java_versions) }}
        exclude:
            - luceeVersion: 5.4/stable/light
              javaVersion: 21
            - luceeVersion: 5.4/stable/light
              javaVersion: 24
            - luceeVersion: 5.4/stable/light
              javaVersion: 24
            - luceeVersion: 6.0/stable/zero
              javaVersion: 21
            - luceeVersion: 6.0/stable/zero
              javaVersion: 24
            - luceeVersion: 6.0/stable/zero
              javaVersion: 24
            - luceeVersion: 6.1/stable/zero
              javaVersion: 24
            - luceeVersion: 6.1/stable/zero
              javaVersion: 24
    env:
        luceeVersionQuery: ${{ matrix.luceeVersion }}
        compile: ${{ github.event.inputs.compile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.javaVersion}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: ${{ github.event.inputs.java_distribution }}
      - name: Cache Maven packages
        if: always()
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v4
        if: always()
        with:
          path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads
      - name: Set up MySQL (local)
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE lucee' -uroot -proot
          mysql -e 'CREATE USER "lucee"@"localhost" IDENTIFIED WITH mysql_native_password BY "lucee";' -uroot -proot
          mysql -e 'GRANT ALL PRIVILEGES ON lucee.* TO "lucee"@"localhost"' -uroot -proot
          mysql -e 'CREATE DATABASE lucee_fallback' -uroot -proot
          mysql -e 'CREATE USER "lucee_fallback"@"localhost" IDENTIFIED WITH mysql_native_password BY "lucee_fallback";' -uroot -proot
          mysql -e 'GRANT ALL PRIVILEGES ON lucee_fallback.* TO "lucee_fallback"@"localhost"' -uroot -proot
      - name: Run Microbenches
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/custom/benchmark
          execute: /index.cfm
          extensions: 7E673D15-D87C-41A6-8B5F1956528C605F #mysql
          luceeVersionQuery: ${{ matrix.luceeVersion }}
        env:
          BENCHMARK_CYCLES: ${{ github.event.inputs.never_rounds }}
          BENCHMARK_ONCE_CYCLES: ${{ github.event.inputs.once_rounds }}
          BENCHMARK_FILTER: ${{ github.event.inputs.benchmark_filter }}
          EXELOG: ${{ github.event.inputs.exeLog }}
          LUCEE_DEBUGGING_MAXPAGEPARTS: 0
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results-${{ strategy.job-index }}
          path: ${{ github.workspace }}/custom/benchmark/artifacts

  report:
    runs-on: ubuntu-latest
    if: always()
    needs: [ benchmarks ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21 / Temurin
        uses: actions/setup-java@v4
        with:
            java-version: 21
            distribution: 'temurin'
      - name: Cache Maven packages
        if: always()
        uses: actions/cache@v4
        with:
            path: ~/.m2
            key: maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v4
        if: always()
        with:
            path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
            key: lucee-downloads
      - uses: actions/download-artifact@v4
        with:
            path: ${{ github.workspace }}/custom/benchmark/artifacts
            merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R ${{ github.workspace }}/custom/benchmark/artifacts
      - name: Generate Report
        uses: lucee/script-runner@main
        with:
            webroot: ${{ github.workspace }}/custom/benchmark
            execute: /report.cfm
            luceeVersionQuery: 6/stable/zero
            extensions:  D46B46A9-A0E3-44E1-D972A04AC3A8DC10 #cfchart
        env:
          BENCHMARK_FILTER: ${{ github.event.inputs.benchmark_filter }}
          EXELOG: ${{ github.event.inputs.exeLog }}
          JAVA_DISTRIBUTION: ${{ github.event.inputs.java_distribution }}
          BENCHMARK_CYCLES: ${{ github.event.inputs.never_rounds }}
          BENCHMARK_ONCE_CYCLES: ${{ github.event.inputs.once_rounds }}
          
