name: Loader Checks

on:
  workflow_dispatch:
    inputs:
      lucee_versions:
        required: false
        description: Lucee Versions (json)
        default: '[ "6.2/all/jar", "5.4/all/jar" ]'
        type: string
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        luceeVersion: ${{ fromJSON(github.event.inputs.lucee_versions) }}
        javaVersion: [ 11 ]
    env:
        luceeVersionQuery: ${{ matrix.luceeVersion }}
        compile: ${{ github.event.inputs.compile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.javaVersion}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: "temurin"
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v4
        if: always()
        with:
          path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads
      - name: Cache Lucee Express files
        uses: actions/cache@v4
        if: always()
        with:
          path: /home/runner/work/lucee-testlab/lucee-testlab/lucee-express-cache/
          key: lucee-express
      - name: Download Lucee Express
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/custom/axis
          execute: /fetch-express.cfm
          luceeVersionQuery: ${{ matrix.luceeVersion }}
        env:
          fetch: ${{ matrix.luceeVersion }}
      - name: Run Express, shutdown, deploy 7 core, startup again
        run: |
          ./express/bin/startup.sh
          echo "sleeping for 10s to allow lucee to deploy and startup...."
          sleep 5
          curl --fail http://127.0.0.1:8888
          ./express/bin/shutdown.sh
          echo "downloading 7 core lco into /deploy"
          curl --fail https://cdn.lucee.org/7.0.0.227-SNAPSHOT.lco -o ./express/lucee-server/deploy/7.0.0.227-SNAPSHOT.lco -s
          ./express/bin/startup.sh
          echo "sleeping for 10s to allow lucee to re-deploy and startup...."
          sleep 5
          curl --fail http://127.0.0.1:8888
          ./express/bin/shutdown.sh
      - name: Debug Express exception.log
        if: failure()
        run: |
            echo "------deploy.log----------"
            cat express/lucee-server/context/logs/deploy.log
            echo "------exception.log----------"
            cat express/lucee-server/context/logs/exception.log