name: ORM tests (Ortus Ext)

on:
  workflow_dispatch:
    inputs:
      lucee_versions:
        required: false
        description: Lucee Versions (json)
        default: '[ "7.0/snapshot/light", "6.2/snapshot/light", "6.2/stable/light", "5.4/stable/light" ]'
        type: string
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # max-parallel: 1
      matrix:
        luceeVersion: ${{ fromJSON(github.event.inputs.lucee_versions) }}
        javaVersion: [ 21, 11 ]
        exclude:
            - luceeVersion: 5.4/stable/light
              javaVersion: 21
        
    env:
        luceeVersionQuery: ${{ matrix.luceeVersion }}
        compile: ${{ github.event.inputs.compile }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.javaVersion }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.javaVersion }}
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: maven-cache
    - name: Cache Lucee files
      uses: actions/cache@v4
      if: always()
      with:
        path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
        key: lucee-downloads
    - name: Checkout Lucee
      uses: actions/checkout@v4
      with:
        repository: lucee/lucee
        path: lucee
    - name: Set up MySQL (local)
      run: |
        sudo systemctl start mysql
        mysql -e 'CREATE DATABASE lucee' -uroot -proot
        mysql -e 'CREATE USER "lucee"@"localhost" IDENTIFIED WITH mysql_native_password BY "lucee";' -uroot -proot
        mysql -e 'GRANT ALL PRIVILEGES ON lucee.* TO "lucee"@"localhost"' -uroot -proot
    - name: Set up Postgres (local)
      run: |
        sudo /etc/init.d/postgresql start
        sudo -u postgres psql -c 'create database lucee;'
        sudo -u postgres psql -c "create user lucee with encrypted password 'lucee'";
        sudo -u postgres psql -c 'grant all privileges on database lucee to lucee;'
        sudo -u postgres psql -c 'grant all on schema public to lucee;' -d lucee
    
    - name: Run Lucee Test Suite, testLabels="orm"
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersion: ${{ env.luceeVersion }}
        luceeVersionQuery: ${{ env.luceeVersionQuery }}
        extensions: D062D72F-F8A2-46F0-8CBC91325B2F067B # ortus orm
        postCleanup: false
      env:
        testLabels: orm
        MYSQL_SERVER: localhost
        MYSQL_USERNAME: lucee
        MYSQL_PASSWORD: lucee
        MYSQL_PORT: 3306
        MYSQL_DATABASE: lucee
        POSTGRES_SERVER: localhost
        POSTGRES_USERNAME: lucee
        POSTGRES_PASSWORD: lucee
        POSTGRES_PORT: 5432
        POSTGRES_DATABASE: lucee
    - name: Debug logs
      if: failure()
      run: |
        s -lR /home/runner/work/_actions/lucee/script-runner/main/temp/lucee/lucee-server/
        echo "------ deploy.log ----------"
        cat /home/runner/work/_actions/lucee/script-runner/main/temp/lucee/lucee-server/context/logs/deploy.log
        echo "------ rest.log ----------"
        cat /home/runner/work/_actions/lucee/script-runner/main/temp/lucee/lucee-server/context/logs/rest.log
        echo "------ application.log ----------"
        cat /home/runner/work/_actions/lucee/script-runner/main/temp/lucee/lucee-server/context/logs/application.log
        echo "------ exception.log ----------"
        cat /home/runner/work/_actions/lucee/script-runner/main/temp/lucee/lucee-server/context/logs/exception.log